<?php

namespace VanBundle\Repository;

/**
 * AcilisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcilisRepository extends \Doctrine\ORM\EntityRepository
{
}
