<?php

namespace VanBundle\Repository;

/**
 * EmlakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmlakRepository extends \Doctrine\ORM\EntityRepository
{
}
