<?php

namespace VanBundle\Repository;

/**
 * EtkinlikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtkinlikRepository extends \Doctrine\ORM\EntityRepository
{
}
