<?php

namespace VanBundle\Repository;

/**
 * OtoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtoRepository extends \Doctrine\ORM\EntityRepository
{
}
