<?php

namespace VanBundle\Repository;

/**
 * ReklamKategoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReklamKategoriRepository extends \Doctrine\ORM\EntityRepository
{
}
