<?php

namespace VanBundle\Repository;

/**
 * ReklamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReklamRepository extends \Doctrine\ORM\EntityRepository
{
}
