<?php

namespace VanBundle\Repository;

/**
 * Seri_ilanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Seri_ilanRepository extends \Doctrine\ORM\EntityRepository
{
}
