<?php

namespace VanBundle\Repository;

/**
 * SeriIlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeriIlanRepository extends \Doctrine\ORM\EntityRepository
{
}
