<?php

namespace VanBundle\Repository;

/**
 * YasamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YasamRepository extends \Doctrine\ORM\EntityRepository
{
}
